name: Check PR Title for Issue Link

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title includes issue link
        run: |
          echo "Checking PR title: ${{ github.event.pull_request.title }}"
          TITLE="${{ github.event.pull_request.title }}"
          if echo "$TITLE" | grep -Eio 'closes #[0-9]+'; then
            echo "✅ PR title includes a closes #<number> reference."
          else
            echo "❌ PR title must include 'closes #<number>'."
            exit 1
          fi